-- Replication user
CREATE USER replicator WITH REPLICATION ENCRYPTED PASSWORD 'reppass';
GRANT ALL PRIVILEGES ON DATABASE test TO replicator;

-- Sample table
CREATE TABLE IF NOT EXISTS users (
  id SERIAL PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);